const pool=require('../config/db');
const {getAllOutcomes}=require('../models/troubleshootOutcomeModel');
const {getIncidentStats,syncIncidentCandidates,issueDescriptor,getIncidentDetectionPolicy}=require('../models/incidentModel');
const MANILA_OFFSET_MS=8*60*60*1000;
function toDate(v){const d=v?new Date(v):null;return d&&!Number.isNaN(d.getTime())?d:null}
function manilaDayKey(v){const d=toDate(v);if(!d)return null;return new Date(d.getTime()+MANILA_OFFSET_MS).toISOString().slice(0,10)}
function normLoc(v){const s=String(v||'Unknown').trim();return /calaca/i.test(s)?'Calaca':(s||'Unknown')}
function pct(a,b){return b?Math.round(a/b*100):0}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function inRange(v,days){const d=toDate(v);return d&&(!days||d>=new Date(Date.now()-days*86400000))}
function ticketResolved(t){return ['Resolved','Archived'].includes(String(t.status||''))}
function issueLabel(t){return issueDescriptor(t)?.label||String(t.category||'Other Support Concern').trim()}

async function getAdminAnalytics(req,res){try{
 await syncIncidentCandidates();
 const [ur,tr,rr,sr]=await Promise.all([
   pool.query(`SELECT id, accountName, accountNumber, location, status, created_at FROM users WHERE role='user'`),
   pool.query(`SELECT t.*,u.location,u.accountNumber,u.accountName FROM tickets t LEFT JOIN users u ON u.id=t.user_id ORDER BY t.created_at DESC`),
   pool.query(`SELECT tr.*,u.location FROM technician_requests tr LEFT JOIN users u ON u.id=tr.user_id ORDER BY tr.created_at DESC`),
   pool.query(`SELECT pt.*,u.location,p.plan_name FROM prepaid_transactions pt LEFT JOIN users u ON u.id=pt.user_id LEFT JOIN prepaid_plans p ON p.id=pt.plan_id WHERE pt.status='completed' AND pt.reference_no LIKE 'POS-%' ORDER BY pt.transaction_date DESC`),
 ]);
 const outcomes=await getAllOutcomes();const incidents=await getIncidentStats();const incidentDetectionPolicy=getIncidentDetectionPolicy();const customers=ur[0],allTickets=tr[0],allTech=rr[0],allSales=sr[0];
 const locationFilter=String(req.query.location||'').trim();const rawDays=Number(req.query.days||30);const days=Number.isFinite(rawDays)&&rawDays>0?rawDays:null;const byLoc=r=>!locationFilter||normLoc(r.location)===normLoc(locationFilter);
 const activeCustomers=customers.filter(c=>String(c.status||'active')==='active'&&byLoc(c));const tickets=allTickets.filter(t=>byLoc(t)&&inRange(t.created_at,days));const tech=allTech.filter(t=>byLoc(t)&&inRange(t.created_at,days));const sales=allSales.filter(s=>byLoc(s)&&inRange(s.transaction_date||s.created_at,days));const outcomeRows=outcomes.filter(o=>byLoc(o)&&inRange(o.created_at,days));const incidentRows=incidents.filter(i=>byLoc(i)&&inRange(i.created_at,days));
 const today=manilaDayKey(new Date());const salesToday=sales.filter(s=>manilaDayKey(s.transaction_date||s.created_at)===today);const ticketsToday=tickets.filter(t=>manilaDayKey(t.created_at)===today);const resolved=tickets.filter(ticketResolved);const resolvedToday=resolved.filter(t=>manilaDayKey(t.updated_at||t.created_at)===today);const resolutionHours=resolved.map(t=>{const a=toDate(t.created_at),b=toDate(t.updated_at);return a&&b?Math.max(0,(b-a)/3600000):null}).filter(v=>v!=null);
 const issueMap={};tickets.forEach(t=>{const k=issueLabel(t);issueMap[k]=(issueMap[k]||0)+1});const topIssues=Object.entries(issueMap).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,count])=>({label,count}));const userTickets={};tickets.forEach(t=>userTickets[t.user_id]=(userTickets[t.user_id]||0)+1);const repeatUsers=Object.values(userTickets).filter(v=>v>=2).length;
 const locs=['Balayan','Calaca','Lian','Calatagan','Nasugbu','Lemery'];const locationMap={};for(const loc of locs){const subscribers=customers.filter(c=>String(c.status||'active')==='active'&&normLoc(c.location)===loc).length;const support=allTickets.filter(t=>normLoc(t.location)===loc&&inRange(t.created_at,days)).length;const technicians=allTech.filter(t=>normLoc(t.location)===loc&&inRange(t.created_at,days)).length;locationMap[loc]={location:loc,subscribers,support,technicians,supportPer100:subscribers?Number((support/subscribers*100).toFixed(1)):0}}
 const assessments=outcomeRows.filter(o=>['resolved','unresolved'].includes(o.outcome));const selfResolved=assessments.filter(o=>o.outcome==='resolved').length;const ticketEscalations=outcomeRows.filter(o=>o.outcome==='ticket').length;const techEsc=outcomeRows.filter(o=>o.outcome==='technician').length;const guideMap={};assessments.forEach(o=>{const key=`${o.model_name||o.model_id} — ${o.issue_label}`;if(!guideMap[key])guideMap[key]={guide:key,resolved:0,unresolved:0,total:0};guideMap[key][o.outcome]+=1;guideMap[key].total+=1});const guidePerformance=Object.values(guideMap).map(g=>({...g,resolutionRate:pct(g.resolved,g.total)})).sort((a,b)=>b.total-a.total).slice(0,10);
 const trend=[];for(let i=6;i>=0;i--){const date=new Date(Date.now()-i*86400000);const key=manilaDayKey(date);trend.push({date:key,label:date.toLocaleDateString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric'}),sales:Number(sales.filter(s=>manilaDayKey(s.transaction_date||s.created_at)===key).reduce((sum,s)=>sum+Number(s.amount||0),0).toFixed(2)),support:tickets.filter(t=>manilaDayKey(t.created_at)===key).length,resolved:resolved.filter(t=>manilaDayKey(t.updated_at||t.created_at)===key).length})}
 const salesByPlan={};sales.forEach(s=>{const k=s.plan_name||`Plan ${s.plan_id}`;if(!salesByPlan[k])salesByPlan[k]={label:k,revenue:0,count:0};salesByPlan[k].revenue+=Number(s.amount||0);salesByPlan[k].count++});const salesByLocation={};sales.forEach(s=>{const k=normLoc(s.location);if(!salesByLocation[k])salesByLocation[k]={location:k,revenue:0,count:0};salesByLocation[k].revenue+=Number(s.amount||0);salesByLocation[k].count++});
 const activeIncidents=incidentRows.filter(i=>i.status==='confirmed');const recentTickets=tickets.slice(0,8).map(t=>({...t,issue_label:issueLabel(t)}));const candidates=incidentRows.filter(i=>i.status==='candidate');const hotspot=Object.values(locationMap).sort((a,b)=>b.supportPer100-a.supportPer100)[0]||null;const topIssue=topIssues[0]||null;const insights=[];if(candidates.length)insights.push({severity:'warning',title:'Possible common issue',text:`${candidates.length} incident candidate${candidates.length>1?'s':''} require Admin review.`});if(hotspot&&hotspot.support>0)insights.push({severity:'info',title:'Location hotspot',text:`${hotspot.location} recorded ${hotspot.supportPer100} support interactions per 100 active subscribers in this period (${hotspot.support} ticket${hotspot.support===1?'':'s'}).`});if(topIssue)insights.push({severity:'info',title:'Top support concern',text:`${topIssue.label} is the most reported concern (${topIssue.count} reports).`});if(assessments.length)insights.push({severity:'info',title:'Self-service performance',text:`Verified troubleshooting resolved ${pct(selfResolved,assessments.length)}% of ${assessments.length} completed troubleshooting assessment${assessments.length===1?'':'s'}.`});
 return res.json({filters:{days,location:locationFilter||null},kpis:{salesToday:Number(salesToday.reduce((s,r)=>s+Number(r.amount||0),0).toFixed(2)),supportToday:ticketsToday.length,resolvedToday:resolvedToday.length,technicianRequests:tech.filter(t=>t.status!=='Cancelled').length,technicianEscalations:techEsc,totalRevenue:Number(sales.reduce((s,r)=>s+Number(r.amount||0),0).toFixed(2)),posTransactions:sales.length,activeSubscribers:activeCustomers.length,totalTickets:tickets.length,resolvedTickets:resolved.length,resolutionRate:pct(resolved.length,tickets.length),avgResolutionHours:Number(avg(resolutionHours).toFixed(1)),repeatContactRate:pct(repeatUsers,Object.keys(userTickets).length),selfServiceResolutionRate:pct(selfResolved,assessments.length),selfServiceAssessments:assessments.length,ticketEscalations,technicianSelfServiceEscalations:techEsc,activeIncidents:activeIncidents.length,incidentCandidates:candidates.length},topIssues,locations:Object.values(locationMap).filter(i=>!locationFilter||i.location===normLoc(locationFilter)),guidePerformance,trend,salesByPlan:Object.values(salesByPlan).sort((a,b)=>b.revenue-a.revenue),salesByLocation:Object.values(salesByLocation).sort((a,b)=>b.revenue-a.revenue),technician:{total:tech.length,completed:tech.filter(t=>t.status==='Completed').length,scheduled:tech.filter(t=>t.status==='Scheduled').length,pending:tech.filter(t=>['Submitted','Under Review'].includes(t.status)).length},recentTickets,incidents:incidentRows,incidentDetectionPolicy,insights});
 }catch(e){console.error('ADMIN ANALYTICS ERROR:',e);return res.status(500).json({error:'Unable to load business analytics.'})}}
module.exports={getAdminAnalytics};
