const pool = require('../config/db');
const { syncIncidentCandidates, listIncidents, getIncidentById, getActiveIncidentsForLocation, confirmIncident, dismissIncident, resolveIncident } = require('../models/incidentModel');
const { createAdminNotification, createNotification } = require('../models/notificationModel');
const { notifySafely } = require('../utils/safeNotification');

async function notifyNewCandidates(candidates){for(const c of candidates){await notifySafely('INCIDENT CANDIDATE',()=>createAdminNotification({type:'admin_incident',message:`Possible common issue: ${c.distinctSubscribers} subscribers in ${c.location} reported ${c.issueLabel}. Review before declaring an incident.`}))}}
async function listAdminIncidents(req,res){try{const created=await syncIncidentCandidates(6);await notifyNewCandidates(created);const incidents=await listIncidents({status:req.query.status||null});return res.json({incidents,newlyDetected:created.length})}catch(e){console.error('LIST INCIDENTS ERROR:',e);return res.status(500).json({error:'Unable to load support incidents.'})}}
async function getMyIncidents(req,res){try{return res.json({incidents:await getActiveIncidentsForLocation(req.user.location)})}catch(e){console.error('GET CUSTOMER INCIDENTS ERROR:',e);return res.status(500).json({error:'Unable to load service advisories.'})}}
async function confirmAdminIncident(req,res){try{const incident=await confirmIncident(req.params.id,req.user.id,req.body?.notes);if(!incident)return res.status(404).json({error:'Incident not found.'});const [users]=await pool.query(`SELECT id, accountNumber FROM users WHERE role='user' AND status='active' AND location=?`,[incident.location]);await notifySafely('CONFIRM INCIDENT',async()=>{for(const u of users){await createNotification({user_id:u.id,account_number:u.accountNumber,type:'service_incident',message:`Service advisory for ${incident.location}: ${incident.issue_label}. Descallar Satellite Services is reviewing this confirmed common issue. You may still submit an individual concern if your situation is different.`})}});return res.json({message:'Incident confirmed.',incident})}catch(e){console.error('CONFIRM INCIDENT ERROR:',e);return res.status(500).json({error:'Unable to confirm incident.'})}}
async function dismissAdminIncident(req,res){try{if(!await getIncidentById(req.params.id))return res.status(404).json({error:'Incident not found.'});return res.json({message:'Possible incident dismissed. Customer tickets were not changed.',incident:await dismissIncident(req.params.id,req.body?.notes)})}catch(e){console.error('DISMISS INCIDENT ERROR:',e);return res.status(500).json({error:'Unable to dismiss incident.'})}}
async function resolveAdminIncident(req,res){try{const incident=await resolveIncident(req.params.id,req.body?.notes);if(!incident)return res.status(404).json({error:'Incident not found.'});return res.json({message:'Incident marked resolved.',incident})}catch(e){console.error('RESOLVE INCIDENT ERROR:',e);return res.status(500).json({error:'Unable to resolve incident.'})}}
module.exports={listAdminIncidents,getMyIncidents,confirmAdminIncident,dismissAdminIncident,resolveAdminIncident};
