import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, MapPin, RefreshCw, ShieldCheck, XCircle } from 'lucide-react';
import incidentApi from '../../api/incidentApi';
const style={candidate:'bg-amber-100 text-amber-800',confirmed:'bg-red-100 text-red-700',resolved:'bg-green-100 text-green-700',dismissed:'bg-slate-100 text-slate-600'};
const fmt=v=>v?new Date(v).toLocaleString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
export default function AdminIncidents(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await incidentApi.getAdminIncidents();setItems(r.data?.incidents||[])}catch(e){setError(e.response?.data?.error||'Unable to load incidents.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const groups=useMemo(()=>({c:items.filter(i=>i.status==='candidate'),a:items.filter(i=>i.status==='confirmed'),h:items.filter(i=>['resolved','dismissed'].includes(i.status))}),[items]);
 const act=async(i,a)=>{const notes=window.prompt('Optional Admin note:','')??'';setBusy(i.id);try{if(a==='confirm')await incidentApi.confirm(i.id,notes);if(a==='dismiss')await incidentApi.dismiss(i.id,notes);if(a==='resolve')await incidentApi.resolve(i.id,notes);await load()}catch(e){setError(e.response?.data?.error||'Unable to update incident.')}finally{setBusy('')}};
 const Card=({i})=><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${style[i.status]}`}>{i.status}</span><span className="flex items-center gap-1 text-xs text-slate-500"><MapPin size={12}/>{i.location}</span></div><h3 className="mt-2 font-black text-slate-900">{i.issue_label}</h3><p className="mt-1 text-xs text-slate-500">{i.distinct_subscribers} distinct subscribers · {i.report_count} reports</p></div><div className="text-right text-[10px] text-slate-400"><p>First {fmt(i.first_reported_at)}</p><p>Latest {fmt(i.last_reported_at)}</p></div></div>{i.notes&&<p className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><b>Admin note:</b> {i.notes}</p>}{i.status==='candidate'&&<div className="mt-4 flex gap-2"><button disabled={busy===i.id} onClick={()=>act(i,'confirm')} className="flex items-center gap-1 rounded-xl bg-[#cc0000] px-3 py-2 text-xs font-bold text-white"><ShieldCheck size={14}/>Confirm</button><button disabled={busy===i.id} onClick={()=>act(i,'dismiss')} className="flex items-center gap-1 rounded-xl border px-3 py-2 text-xs font-bold text-slate-600"><XCircle size={14}/>Dismiss</button></div>}{i.status==='confirmed'&&<button disabled={busy===i.id} onClick={()=>act(i,'resolve')} className="mt-4 flex items-center gap-1 rounded-xl bg-green-600 px-3 py-2 text-xs font-bold text-white"><CheckCircle2 size={14}/>Mark Resolved</button>}</div>;
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-xl font-black text-slate-900">Incidents & Common Issues</h1><p className="mt-1 text-xs text-slate-500">Detection requires 3 distinct subscribers in the same location within 6 hours. Admin confirmation is mandatory.</p></div><button onClick={load} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-bold"><RefreshCw size={14}/>Refresh Detection</button></div>{error&&<div className="rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</div>}<div className="grid grid-cols-3 gap-3"><div className="rounded-2xl bg-amber-50 p-4"><p className="text-xs font-bold text-amber-700">Needs Review</p><p className="text-3xl font-black">{groups.c.length}</p></div><div className="rounded-2xl bg-red-50 p-4"><p className="text-xs font-bold text-red-700">Active</p><p className="text-3xl font-black">{groups.a.length}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">History</p><p className="text-3xl font-black">{groups.h.length}</p></div></div>{loading?<div className="rounded-2xl bg-white p-10 text-center text-sm text-slate-400">Checking support patterns...</div>:<><section><div className="mb-3 flex items-center gap-2"><AlertTriangle size={16} className="text-amber-600"/><h2 className="text-sm font-black">Possible Common Issues</h2></div>{groups.c.length?<div className="grid gap-3 lg:grid-cols-2">{groups.c.map(i=><Card key={i.id} i={i}/>)}</div>:<div className="rounded-2xl border border-dashed bg-white p-6 text-center text-xs text-slate-400">No current candidate meets the threshold.</div>}</section><section><h2 className="mb-3 mt-5 text-sm font-black">Confirmed Active Incidents</h2>{groups.a.length?<div className="grid gap-3 lg:grid-cols-2">{groups.a.map(i=><Card key={i.id} i={i}/>)}</div>:<div className="rounded-2xl border border-dashed bg-white p-6 text-center text-xs text-slate-400">No active confirmed incidents.</div>}</section>{groups.h.length>0&&<section><h2 className="mb-3 mt-5 text-sm font-black">Incident History</h2><div className="grid gap-3 lg:grid-cols-2">{groups.h.map(i=><Card key={i.id} i={i}/>)}</div></section>}</>}</div>
}
