import { useEffect, useMemo, useState } from 'react';
import { Download } from 'lucide-react';
import { AreaChart, Area, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import analyticsApi from '../../api/analyticsApi';

const LOC=['','Balayan','Calaca','Lian','Calatagan','Nasugbu','Lemery'];
const TABS=[['overview','Overview'],['sales','Sales Analytics'],['support','Subscriber Support'],['service','Technician / Service']];
function Metric({label,value,sub}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-2xl font-black text-slate-900">{value}</p><p className="mt-1 text-[11px] text-slate-500">{sub}</p></div>}
function Bars({items,labelKey='label',valueKey='count',format=v=>v}){const max=Math.max(...items.map(i=>Number(i[valueKey]||0)),1);return <div className="space-y-3">{items.length?items.map((i,x)=><div key={`${i[labelKey]}-${x}`}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate font-semibold text-slate-700">{i[labelKey]}</span><b>{format(i[valueKey])}</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-[#cc0000]" style={{width:`${Math.max(4,Number(i[valueKey]||0)/max*100)}%`}}/></div></div>):<p className="py-6 text-center text-xs text-slate-400">No data in this period.</p>}</div>}

export default function AdminAnalytics(){
 const[tab,setTab]=useState('overview'),[days,setDays]=useState('30'),[location,setLocation]=useState(''),[data,setData]=useState(null),[loading,setLoading]=useState(true);
 useEffect(()=>{let a=true;setLoading(true);analyticsApi.getAdminAnalytics({days,location:location||undefined}).then(r=>a&&setData(r.data)).catch(console.error).finally(()=>a&&setLoading(false));return()=>{a=false}},[days,location]);
 const k=data?.kpis||{}; const locations=useMemo(()=>[...(data?.locations||[])].sort((a,b)=>b.supportPer100-a.supportPer100),[data]);
 const exportCsv=()=>{const rows=[['CignalCare+ Business Analytics'],['Period',`${days} days`],['Location',location||'All Locations'],[],['SUMMARY'],['Metric','Value'],['POS Revenue',k.totalRevenue||0],['POS Transactions',k.posTransactions||0],['Active Subscribers',k.activeSubscribers||0],['Support Tickets',k.totalTickets||0],['Resolution Rate',`${k.resolutionRate||0}%`],['Self-Service Resolution',`${k.selfServiceResolutionRate||0}%`],['Repeat Contact Rate',`${k.repeatContactRate||0}%`],[],['TOP ISSUES'],['Issue','Reports'],...(data?.topIssues||[]).map(i=>[i.label,i.count]),[],['LOCATION SUPPORT'],['Location','Subscribers','Support','Support per 100'],...(data?.locations||[]).map(i=>[i.location,i.subscribers,i.support,i.supportPer100]),[],['GUIDE PERFORMANCE'],['Guide','Resolved','Unresolved','Resolution Rate'],...(data?.guidePerformance||[]).map(g=>[g.guide,g.resolved,g.unresolved,`${g.resolutionRate}%`])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob(['\ufeff',csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`cignalcare-business-analytics-${Date.now()}.csv`;a.click();URL.revokeObjectURL(url)};
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-xl font-black text-slate-900">Business Analytics</h1><p className="mt-1 text-xs text-slate-500">Sales performance and subscriber-support intelligence for management decisions.</p></div><div className="flex flex-wrap gap-2"><select value={days} onChange={e=>setDays(e.target.value)} className="rounded-xl border bg-white px-3 py-2 text-xs font-semibold"><option value="7">Last 7 Days</option><option value="30">Last 30 Days</option><option value="90">Last 90 Days</option><option value="365">Last 12 Months</option></select><select value={location} onChange={e=>setLocation(e.target.value)} className="rounded-xl border bg-white px-3 py-2 text-xs font-semibold"><option value="">All Locations</option>{LOC.filter(Boolean).map(x=><option key={x}>{x}</option>)}</select><button disabled={loading} onClick={exportCsv} className="flex items-center gap-2 rounded-xl bg-[#cc0000] px-3 py-2 text-xs font-bold text-white disabled:opacity-50"><Download size={14}/>Export</button></div></div><div className="flex gap-2 overflow-x-auto border-b">{TABS.map(([id,l])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap border-b-2 px-3 py-2 text-xs font-bold ${tab===id?'border-[#cc0000] text-[#cc0000]':'border-transparent text-slate-500'}`}>{l}</button>)}</div>
 {tab==='overview'&&<><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="POS Revenue" value={loading?'...':`₱${Number(k.totalRevenue||0).toLocaleString()}`} sub={`${k.posTransactions||0} in-store transactions`}/><Metric label="Support Resolution" value={`${k.resolutionRate||0}%`} sub={`${k.totalTickets||0} tickets`}/><Metric label="Self-Service Success" value={`${k.selfServiceResolutionRate||0}%`} sub={`${k.selfServiceAssessments||0} troubleshoot assessments`}/><Metric label="Active Incidents" value={k.activeIncidents||0} sub={`${k.incidentCandidates||0} candidates need review`}/></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-4"><h2 className="text-sm font-black">7-Day Operations Trend</h2><div className="mt-3 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data?.trend||[]}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Area dataKey="support" stroke="#cc0000" fill="#fee2e2" name="Support"/><Area dataKey="resolved" stroke="#16a34a" fill="transparent" name="Resolved"/></AreaChart></ResponsiveContainer></div></div><div className="rounded-2xl border bg-white p-4"><h2 className="text-sm font-black">Smart Management Insights</h2><div className="mt-3 space-y-2">{(data?.insights||[]).map((i,x)=><div key={x} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-black">{i.title}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{i.text}</p></div>)}</div></div></div></>}
 {tab==='sales'&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><Metric label="In-Store Revenue" value={`₱${Number(k.totalRevenue||0).toLocaleString()}`} sub="Excludes online PayMongo load requests"/><Metric label="POS Transactions" value={k.posTransactions||0} sub="Completed in-store transactions"/><Metric label="Revenue Today" value={`₱${Number(k.salesToday||0).toLocaleString()}`} sub="Philippines time"/></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-4"><h2 className="text-sm font-black">Top Plans by Revenue</h2><div className="mt-4"><Bars items={data?.salesByPlan||[]} valueKey="revenue" format={v=>`₱${Number(v).toLocaleString()}`}/></div></div><div className="rounded-2xl border bg-white p-4"><h2 className="text-sm font-black">POS Revenue by Location</h2><div className="mt-4"><Bars items={data?.salesByLocation||[]} labelKey="location" valueKey="revenue" format={v=>`₱${Number(v).toLocaleString()}`}/></div></div></div></>}
 {tab==='support'&&<><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Resolution Rate" value={`${k.resolutionRate||0}%`} sub={`${k.totalTickets||0} tickets`}/><Metric label="Self-Service Success" value={`${k.selfServiceResolutionRate||0}%`} sub="Real troubleshoot outcomes"/><Metric label="Repeat Contact Rate" value={`${k.repeatContactRate||0}%`} sub="Subscribers with 2+ tickets"/><Metric label="Average Resolution" value={`${k.avgResolutionHours||0} hrs`} sub="Resolved ticket turnaround"/></div><div className="grid gap-4 xl:grid-cols-2"><div className="rounded-2xl border bg-white p-4"><h2 className="text-sm font-black">Most Common Subscriber Problems</h2><div className="mt-4"><Bars items={data?.topIssues||[]}/></div></div><div className="rounded-2xl border bg-white p-4"><h2 className="text-sm font-black">Location Hotspots</h2><div className="mt-4"><Bars items={locations} labelKey="location" valueKey="supportPer100" format={v=>`${v} / 100 subs`}/></div></div><div className="rounded-2xl border bg-white p-4 xl:col-span-2"><h2 className="text-sm font-black">Troubleshooting Guide Performance</h2><p className="mt-1 text-[11px] text-slate-400">Measured from the existing “Did these steps solve the problem?” flow.</p><div className="mt-4 overflow-x-auto"><table className="min-w-full text-xs"><thead><tr className="border-b text-left text-slate-400"><th className="py-2">Guide</th><th>Resolved</th><th>Unresolved</th><th>Success</th></tr></thead><tbody>{(data?.guidePerformance||[]).map(g=><tr key={g.guide} className="border-b border-slate-100"><td className="py-3 pr-4 font-semibold text-slate-700">{g.guide}</td><td>{g.resolved}</td><td>{g.unresolved}</td><td><span className={`rounded-full px-2 py-1 font-bold ${g.resolutionRate>=60?'bg-green-100 text-green-700':'bg-amber-100 text-amber-700'}`}>{g.resolutionRate}%</span></td></tr>)}</tbody></table>{!(data?.guidePerformance||[]).length&&<p className="py-6 text-center text-slate-400">No troubleshooting outcomes recorded yet.</p>}</div></div></div></>}
 {tab==='service'&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Technician Requests" value={data?.technician?.total||0} sub="Selected period"/><Metric label="Completed" value={data?.technician?.completed||0} sub="Service completed"/><Metric label="Scheduled" value={data?.technician?.scheduled||0} sub="Currently scheduled"/><Metric label="Pending Review" value={data?.technician?.pending||0} sub="Submitted / under review"/></div><div className="rounded-2xl border bg-white p-4"><h2 className="text-sm font-black">Service Demand by Location</h2><div className="mt-4"><Bars items={(data?.locations||[]).sort((a,b)=>b.technicians-a.technicians)} labelKey="location" valueKey="technicians"/></div></div></>}
 </div>}
